version: '3.7'

services:

  app:
    image: yunedobro/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
    depends_on:
      - db
  
  db:
    image: postgres:alpine
    volumes:
      - pgdata-hexlet:/var/lib/postgresql/data
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}


volumes:
  pgdata-hexlet:
